# Oracle DB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##travel_planner
spring.datasource.password=travel1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# JWT
jwt.secret=travel-planner-secret-key-must-be-at-least-32-characters-long
jwt.expiration=1800000

# Server
server.port=8080
# \uADF8\uB85D api
groq.api.key=\uD0A4\uC785\uB825\uD558\uC138\uC694

# ??? api?
kakao.api.key=

# Redis \uC124\uC815
spring.data.redis.host=localhost
spring.data.redis.port=6379