# Oracle DB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##travel_planner
spring.datasource.password=travel1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# JWT
jwt.secret=travel-planner-secret-key-must-be-at-least-32-characters-long
jwt.expiration=1800000

# Server
server.port=8080
# \uADF8\uB85D api


# ??? api?
kakao.api.key=056b1be1440dee519bd6007c28ff34b5

# Redis \uC124\uC815
spring.data.redis.host=localhost
spring.data.redis.port=6379

# \uCE74\uCE74\uC624 \uC778\uC99D \uC815\uBCF4
kakao.client-id=056b1be1440dee519bd6007c28ff34b5
kakao.client-secret=DZa8PD8VVOo0QDy0E1Qme5ZGPt4ecsZB
kakao.redirect-uri=http://localhost:5173/oauth/kakao